deleted file mode 100644
@@ -1,112 +0,0 @@
-import imaplib
-import email
-import logging
-import zmq
-import os
-
-
-
-# Connect to an IMAP server
-def connect(server, user, password):
-    m = imaplib.IMAP4_SSL(server)
-    m.login(user, password)
-    m.select()
-    return m
-
-# Download all attachment files for a given email
-def downloaAttachmentsInEmail(m, emailid, outputdir):
-    resp, data = m.fetch(emailid, "(RFC822)") # "(BODY.PEEK[])")
-    email_body = data[0][1]
-    mail = email.message_from_string(email_body)
-    
-    # read header - for SUBJECT FROM TO
-    for header in [ 'subject', 'to', 'from','date' ]:
-        log.debug('%-8s: %s' % (header.upper(), mail[header]))
-    mail_subject=mail['subject']
-    
-    
-    # check attachment
-    if mail.get_content_maintype() != 'multipart': # no attach
-        return 
-    
-    for part in mail.walk():
-        if part.get_content_maintype() == 'multipart':
-            continue
-        if part.get('Content-Disposition') is None:
-            continue
-    
-        # save attachment
-        if (part.get_filename()):
-            filename = outputdir + '/' + part.get_filename()
-            fp = open(filename, 'wb')
-            fp.write(part.get_payload(decode=True))
-            fp.close()
-            log.debug('Saved file: '+filename)
-            
-
-    # temp = m.store(emailid,'+FLAGS', '\\Seen')
-    # move to Processed and delete
-    # m.copy(emailid, 'Processed')
-    # temp = m.store(emailid, '+FLAGS', r'(\Deleted)')
-    # typ, response = m.expunge() # delete flaged mails
-    log.info('Sending zmq mesg: '+mail_subject+':'+filename)
-    # call ZMQsend(mail_subject+'::'+filename,ZMQserver,ZMQserverPort, ZMQtimeout)   
-    
-
-# Download all the attachment files for all emails in the inbox.
-def downloadAllAttachmentsInInbox(server, user, password, outputdir):
-    m = connect(server, user, password)
-    resp, items = m.search(None, "(ALL)")
-    items = items[0].split()
-    for emailid in items:
-        downloaAttachmentsInEmail(m, emailid, outputdir)
-    
-    #delete mails woth flag DELETE
-    # typ, response = m.expunge()
-    try:
-        m.close()
-    except:
-        pass
-    m.logout()    
-        
-        
-def ZMQsend(message,server,port,timeout):
-    '''
-    Send message to server via ZeroMQ
-    '''
-    serveradd = 'tcp://' + server + ":" + port
-    if click.confirm('Do you want to continue?',default=True):
-        with zmq.Context() as context:
-            context.setsockopt(zmq.LINGER, timeout)
-            with context.socket(zmq.PUSH) as socket:
-                socket.connect(serveradd)
-                socket.send_string(message,zmq.NOBLOCK) # pro timeout, ale nefunguje
-
-
-
-# ---------------------------------------------------------------------
-# MAIL_SERVER='mail.fabob.net'
-# MAIL_USER='bobanovo@fabob.net'
-# MAIL_PASS='micicek'
-MAIL_SERVER='mail.fabob.net'
-MAIL_USER='kone.cloud@fabob.net'
-MAIL_PASS='koneKONEkone'
-OUTDIR='./koneCloud'
-
-ZMQserver="127.0.0.1"
-ZMQserverPort="8899"
-ZMQtimeout=1
-
-if __name__=="__main__":
-    logging.basicConfig()
-    log = logging.getLogger(__name__)
-    log.setLevel('DEBUG')
-    
-    log.info('Starting')
-    log.info('Mail server is set to '+MAIL_SERVER)
-    log.info('Mail user is set to '+MAIL_USER)
-    log.info('Output dir is set to '+OUTDIR)
-    
-    downloadAllAttachmentsInInbox(MAIL_SERVER, MAIL_USER, MAIL_PASS,OUTDIR)
-    
-    
\ No newline at end of file

